<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="vlobanovs-MacBook-Pro.local" name="com.ecofactorqa.awayapi.Set_Away_Invalid" tests="48" failures="0" timestamp="31 Dec 2014 00:42:47 GMT" time="72.348" errors="8">
  <testcase name="test_start_Away_using_two_digit_year" time="0.034" classname="com.ecofactorqa.awayapi.Set_Away_Invalid">
    <error type="java.lang.AssertionError" message="Invalid format for end time expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Invalid format for end time expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ecofactorqa.awayapi.Set_Away_Invalid.test_start_Away_using_two_digit_year(Set_Away_Invalid.java:194)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- test_start_Away_using_two_digit_year -->
  <testcase name="test_start_Away_using_invalid_heat_setpoint_coma" time="0.021" classname="com.ecofactorqa.awayapi.Set_Away_Invalid"/>
  <testcase name="test_start_Away_using_no_hours" time="0.032" classname="com.ecofactorqa.awayapi.Set_Away_Invalid"/>
  <testcase name="test_start_Away_using_past_date" time="0.042" classname="com.ecofactorqa.awayapi.Set_Away_Invalid"/>
  <testcase name="test_start_Away_using_one_digit_day" time="4.325" classname="com.ecofactorqa.awayapi.Set_Away_Invalid">
    <error type="java.lang.AssertionError" message="Expected status 400. Actual status is :200 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Expected status 400. Actual status is :200 expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ecofactorqa.awayapi.Set_Away_Invalid.test_start_Away_using_one_digit_day(Set_Away_Invalid.java:218)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- test_start_Away_using_one_digit_day -->
  <testcase name="test_start_Away_using_invalid_cool_setpoint_negative" time="0.055" classname="com.ecofactorqa.awayapi.Set_Away_Invalid"/>
  <testcase name="test_start_Away_using_invalid_heat_setpoint_empty" time="0.021" classname="com.ecofactorqa.awayapi.Set_Away_Invalid"/>
  <testcase name="test_start_Away_using_invalid_heat_setpoint_null" time="0.048" classname="com.ecofactorqa.awayapi.Set_Away_Invalid">
    <error type="java.lang.AssertionError" message="Missing required attribute expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Missing required attribute expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ecofactorqa.awayapi.Set_Away_Invalid.test_start_Away_using_invalid_heat_setpoint_null(Set_Away_Invalid.java:546)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- test_start_Away_using_invalid_heat_setpoint_null -->
  <testcase name="test_start_Away_using_noT_S" time="0.039" classname="com.ecofactorqa.awayapi.Set_Away_Invalid"/>
  <testcase name="test_start_Away_using_invalid_heat_setpoint_char" time="0.023" classname="com.ecofactorqa.awayapi.Set_Away_Invalid"/>
  <testcase name="test_start_Away_using_invalid_cool_setpoint_char" time="0.024" classname="com.ecofactorqa.awayapi.Set_Away_Invalid"/>
  <testcase name="test_start_Away_using_invalid_heat_setpoint_negative" time="0.067" classname="com.ecofactorqa.awayapi.Set_Away_Invalid"/>
  <testcase name="test_start_Away_using_no_month" time="0.042" classname="com.ecofactorqa.awayapi.Set_Away_Invalid"/>
  <testcase name="test_start_Away_using_invalid_cool_setpoint_boundary_max" time="0.082" classname="com.ecofactorqa.awayapi.Set_Away_Invalid"/>
  <testcase name="test_start_Away_using_noT_space" time="0.033" classname="com.ecofactorqa.awayapi.Set_Away_Invalid"/>
  <testcase name="test_start_Away_using_invalid_cool_setpoint_no_coma_end" time="0.020" classname="com.ecofactorqa.awayapi.Set_Away_Invalid"/>
  <testcase name="test_start_Away_using_invalid_heat_setpoint_no_coma_end" time="0.018" classname="com.ecofactorqa.awayapi.Set_Away_Invalid"/>
  <testcase name="test_start_Away_using_neg_hours" time="0.032" classname="com.ecofactorqa.awayapi.Set_Away_Invalid"/>
  <testcase name="test_start_Away_using_one_digit_sec" time="14.205" classname="com.ecofactorqa.awayapi.Set_Away_Invalid">
    <error type="java.lang.AssertionError" message="Expected status 400. Actual status is :500 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Expected status 400. Actual status is :500 expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ecofactorqa.awayapi.Set_Away_Invalid.test_start_Away_using_one_digit_sec(Set_Away_Invalid.java:322)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- test_start_Away_using_one_digit_sec -->
  <testcase name="test_start_Away_using_neg_sec" time="18.863" classname="com.ecofactorqa.awayapi.Set_Away_Invalid">
    <error type="java.lang.AssertionError" message="Expected status 400. Actual status is :200 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Expected status 400. Actual status is :200 expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ecofactorqa.awayapi.Set_Away_Invalid.test_start_Away_using_neg_sec(Set_Away_Invalid.java:140)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- test_start_Away_using_neg_sec -->
  <testcase name="test_start_Away_using_no_end_time" time="0.026" classname="com.ecofactorqa.awayapi.Set_Away_Invalid"/>
  <testcase name="test_start_Away_using_invalid_heat_setpoint_boundary_max" time="0.057" classname="com.ecofactorqa.awayapi.Set_Away_Invalid"/>
  <testcase name="test_start_Away_using_invalid_heat_setpoint_zero" time="0.091" classname="com.ecofactorqa.awayapi.Set_Away_Invalid"/>
  <testcase name="test_start_Away_using_no_day" time="0.031" classname="com.ecofactorqa.awayapi.Set_Away_Invalid"/>
  <testcase name="test_start_Away_using_invalid_heat_setpoint_one" time="0.045" classname="com.ecofactorqa.awayapi.Set_Away_Invalid"/>
  <testcase name="test_start_Away_using_invalid_cool_setpoint_null" time="0.065" classname="com.ecofactorqa.awayapi.Set_Away_Invalid">
    <error type="java.lang.AssertionError" message="Missing required attribute expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Missing required attribute expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ecofactorqa.awayapi.Set_Away_Invalid.test_start_Away_using_invalid_cool_setpoint_null(Set_Away_Invalid.java:402)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- test_start_Away_using_invalid_cool_setpoint_null -->
  <testcase name="test_start_Away_using_one_digit_month" time="14.645" classname="com.ecofactorqa.awayapi.Set_Away_Invalid">
    <error type="java.lang.AssertionError" message="Expected status 400. Actual status is :200 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Expected status 400. Actual status is :200 expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ecofactorqa.awayapi.Set_Away_Invalid.test_start_Away_using_one_digit_month(Set_Away_Invalid.java:205)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- test_start_Away_using_one_digit_month -->
  <testcase name="test_start_Away_using_incorrect_time_format_dot" time="0.037" classname="com.ecofactorqa.awayapi.Set_Away_Invalid"/>
  <testcase name="test_start_Away_using_invalid_heat_setpoint_five_digit" time="0.064" classname="com.ecofactorqa.awayapi.Set_Away_Invalid"/>
  <testcase name="test_start_Away_using_invalid_cool_setpoint_boundary_min" time="0.090" classname="com.ecofactorqa.awayapi.Set_Away_Invalid"/>
  <testcase name="test_start_Away_using_no_T" time="0.038" classname="com.ecofactorqa.awayapi.Set_Away_Invalid"/>
  <testcase name="test_start_Away_using_invalid_heat_setpoint_boundary_min" time="0.055" classname="com.ecofactorqa.awayapi.Set_Away_Invalid"/>
  <testcase name="test_start_Away_using_incorrect_time_format_semicolons" time="0.032" classname="com.ecofactorqa.awayapi.Set_Away_Invalid"/>
  <testcase name="test_start_Away_using_invalid_cool_setpoint_coma" time="0.031" classname="com.ecofactorqa.awayapi.Set_Away_Invalid"/>
  <testcase name="test_start_Away_using_zero_year" time="0.024" classname="com.ecofactorqa.awayapi.Set_Away_Invalid"/>
  <testcase name="test_start_Away_using_invalid_cool_setpoint_empty" time="0.025" classname="com.ecofactorqa.awayapi.Set_Away_Invalid"/>
  <testcase name="test_start_Away_using_no_minutes" time="0.036" classname="com.ecofactorqa.awayapi.Set_Away_Invalid"/>
  <testcase name="test_start_Away_using_invalid_cool_setpoint_one" time="0.075" classname="com.ecofactorqa.awayapi.Set_Away_Invalid"/>
  <testcase name="test_start_Away_using_invalid_cool_setpoint_five_digit" time="0.057" classname="com.ecofactorqa.awayapi.Set_Away_Invalid"/>
  <testcase name="test_start_Away_using_incorrect_time_format_dash" time="0.441" classname="com.ecofactorqa.awayapi.Set_Away_Invalid"/>
  <testcase name="test_start_Away_using_zero_day" time="0.028" classname="com.ecofactorqa.awayapi.Set_Away_Invalid"/>
  <testcase name="test_start_Away_using_no_year" time="0.035" classname="com.ecofactorqa.awayapi.Set_Away_Invalid"/>
  <testcase name="test_start_Away_using_one_digit_min" time="18.122" classname="com.ecofactorqa.awayapi.Set_Away_Invalid">
    <error type="java.lang.AssertionError" message="Expected status 400. Actual status is :200 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Expected status 400. Actual status is :200 expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.ecofactorqa.awayapi.Set_Away_Invalid.test_start_Away_using_one_digit_min(Set_Away_Invalid.java:309)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- test_start_Away_using_one_digit_min -->
  <testcase name="test_start_Away_using_no_sec" time="0.034" classname="com.ecofactorqa.awayapi.Set_Away_Invalid"/>
  <testcase name="test_start_Away_using_zero_month" time="0.024" classname="com.ecofactorqa.awayapi.Set_Away_Invalid"/>
  <testcase name="test_start_Away_using_no_date" time="0.033" classname="com.ecofactorqa.awayapi.Set_Away_Invalid"/>
  <testcase name="test_start_Away_using_neg_min" time="0.027" classname="com.ecofactorqa.awayapi.Set_Away_Invalid"/>
  <testcase name="test_start_Away_using_invalid_cool_setpoint_zero" time="0.054" classname="com.ecofactorqa.awayapi.Set_Away_Invalid"/>
</testsuite> <!-- com.ecofactorqa.awayapi.Set_Away_Invalid -->
